services:
  wedding-db:
    image: postgres
    volumes:
      - ./.db:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  wedding-server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      wedding-db:
        condition: service_healthy
    restart: unless-stopped

  wedding-web:
    build:
      dockerfile: web.Dockerfile
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_FRONT_URL: ${VITE_FRONT_URL}
    ports:
      - "8086:80"
    env_file:
      - .env
    restart: unless-stopped
